---
- name: Generate Kubernetes join command
  hosts: kubernetes_master
  become: true

  tasks:
    - name: Get kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Store join command
      set_fact:
        kubeadm_join_command: "{{ join_command.stdout }}"

- name: Join worker nodes
  hosts: kubernetes_workers
  become: true

  tasks:
    - name: Join Kubernetes cluster
      shell: "{{ hostvars[groups['kubernetes_master'][0]].kubeadm_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
