[k8s_master]
k8-master-homelab ansible_host=192.168.13.211

[k8s_workers]
k8-wk1-homelab ansible_host=192.168.13.212
k8-wk2-homelab ansible_host=192.168.13.213

[k8s:children]
k8s_master
k8s_workers

[k8s:vars]
ansible_user=viduka
ansible_become=true
